# Generated by Django 4.2.4 on 2024-01-28 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, max_length=255, null=True)),
                ('user_messages', models.JSONField(default=list)),
                ('ai_messages', models.JSONField(default=list)),
                ('text_chunks', models.JSONField(default=list)),
                ('chat_history', models.JSONField(default=list)),
            ],
        ),
    ]
