# Generated by Django 4.2.4 on 2023-11-19 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfChat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textdata',
            name='text_content',
        ),
        migrations.AddField(
            model_name='textdata',
            name='ai_messages',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='textdata',
            name='filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='textdata',
            name='user_messages',
            field=models.JSONField(default=list),
        ),
    ]
