# Generated by Django 4.2.4 on 2023-12-18 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfChat', '0002_remove_textdata_text_content_textdata_ai_messages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='textdata',
            name='text_chunks',
            field=models.JSONField(default=list),
        ),
    ]
