# Generated by Django 4.2.4 on 2023-12-22 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfChat', '0003_textdata_text_chunks'),
    ]

    operations = [
        migrations.AddField(
            model_name='textdata',
            name='chat_history',
            field=models.JSONField(default=list),
        ),
    ]
